---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/colleges-test
    username: postgres
    password: 3sp3r4nz4
  jpa:
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       ddl-auto: create
       jdbc:
        lob:
          non_contextual_creation: true
