---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       ddl-auto: update
       jdbc:
        lob:
          non_contextual_creation: true
